theme:          iiifc-theme
permalink:      pretty

cookbook_url:   ''

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-liquify
#  - jekyll-last-modified-at

highlighter: none

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

exclude: ["Rakefile", "scripts", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

# notification:
#   enabled: true
#   title: This website design is in pre-beta.
#   subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   link: '#'
#   link_label: This is a test link
